worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    server {
        listen 80;
        server_name haveshapp.ir;

        location / {
            proxy_pass http://haveshapp:8080;  # Route requests to haveshapp
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name silo.haveshapp.ir;

        location / {
            proxy_pass http://haveshsilo:8081;  # Route requests to haveshsilo
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
