name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build --tag haveshapp:latest -f HaveshApp/Dockerfile .
        docker push pharzath/haveshapp:latest
